---
title: Oliver Engel Design Portfolio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    section: post
email: oliverengel6@gmail.com
description: Digital product designer based in Seattle, WA.
baseurl: ''
url: http://oliverengel.com
permalink: "/blog/:title"
section: true
netlifycms: true
analytics: false
plugins:
- jekyll-sitemap
sass:
  style: compressed
  sass_dir: _sass
compress_html:
  clippings: all
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- README.md
- LICENSE.txt
- netlify.toml
- feed.xml
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
